spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/flowers?characterEncoding=UTF-8&&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver